baseURL: "https://hugo-profile.netlify.app"
languageCode: "fr"
title: "Portfolio Hugo Perard"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 20
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: AP
      name: AP et Projets
      title: AP et Projets
      url: /projets/
      weight: 1
    - identifier: Stages
      name: Stages
      title: Stages
      url: /stages/
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio Perard Hugo"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Bonjour je m'appelle"
    title: "Hugo"
    subtitle: "Je suis étudiant en BTS SIO SISR"
    content: "Je suis en réseaux dans le bts sio"
    image: /images/photoicone.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Akywayy
        - icon: fab fa-discord
          url: https://discord.gg/PZAkAhF7z
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/hugo-perard-b98584349?utm_source=share_via&utm_content=profile&utm_medium=ios_app
        - icon: fab fa-letterboxd
          url: https://letterboxd.com/Akywayy52

  # About
  about:
    enable: true
    title: "A Propos de moi"
    content: |-
      Je suis un étudiant en réseaux passionné par cette fillière. J'ai commencé une formation en informatique, et je m'intéresse particulièrement a la photographie qui est une de mes principale passions ainsi que les films. .

      Je suis actuellement en premiere année dans mon BTS
    skills:
      enable: true
      title: "Voici quelque langague que j'utilise :"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Commis en job d'été pendant 3 ans"
        company: "Le Grain de Sel"
        companyUrl: "https://www.tripadvisor.fr/Restaurant_Review-g187134-d12790271-Reviews-Le_Grain_de_Sel-Chaumont_Haute_Marne_Grand_Est.html"
        date: "été 2022-2023-2024"
        featuredLink: 
          enable: false
          url: "https://example.com"
        content: "J'étais principalement au poste du chaud et des desserts j'ai beaucoup apprécié l'ambiance de travail"

      - job: "Stage de 4 mois "
        company: "Hotel - Restaurant Le Faudé"
        companyUrl: "https://www.faude.com/fr/accueil"
        date: "2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: J'ai découvert le métier grace a se stage avec ma premiere année de Bac Pro MHR 
          

      - job: "Stage 1 semaine"
        company: "Chez Brodier"
        companyUrl: "https://www.google.com/search?client=ubuntu-sn&hs=c0B&sca_esv=33dfbfdc183bdef6&channel=fs&uds=ABqPDvztZD_Nu18FR6tNPw2cK_RRID6T_A5pSWj1_QXyjND3wkjJ85qlt6BIGkZJrWzJNms67U72pupHPlX18uNtt-YWeI1QGCBR4-Z-5Y98-PNj-sH-PdomkU9LGbuH08NSKaiMExw7&si=APYL9bs7Hg2KMLB-4tSoTdxuOx8BdRvHbByC_AuVpNyh0x2KzSWEnEFVTEtiFjboi5f3V6jNdtQgeW_9wNe-QNx2aiFDgbYNG9q78yUFIkc1p-JWi4k3wjc%3D&q=Brodier+Avis&sa=X&ved=2ahUKEwjSm_aioZ2LAxVzcaQEHWWeMGkQ3PALegQIMhAF&biw=1280&bih=653&dpr=1"
        date: "2021"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: Avec se premier stage j'ai directement apprécié la patisserie qui étais une passion dès mon enfance


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "BAC STMG"
        school: 
          name: "Lycée Privé Oudinot"
          url: "http://www.oudinot.org/"
        date: "2022-2024"
        Résultat: "Admis"
        content: J'ai fais mon Bac STMG pendant deux ans au sein de cet etablissement
        
      - title: "Une Année Bac Pro MHR"
        school:
          name: "Lycée Pro Didedrot"
          url: "https://lyc-diderot-langres.monbureaunumerique.fr/"
        date: "2022"
        content: J'ai fais uniquement une année
        

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Php
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Je suis toujours disponible via mail!
    btnName: Mail
    btnLink: mailto:hugoperard52@outlook.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Droit D'auteurs"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
